### PR TITLE
Add a verification pass right after auto test generated to make sure …

### LINKED ISSUE #13: Add a verification pass
When generating notebooks, after the autotest preprocessor is done inserting tests, do a full pass of the notebook again to catch any possible errors that may have been introduced.

If there is an error, report the cell + contents that produced the error.

### PR DESCRIPTION
**Pull request by wiwang**
…auto-generated tests succeed when using the real solution
resolve #13

### CODE REVIEW

**Comment by wiwang** [comment]
the `Execute` preprocessor is right after `InstantiateTests` preprocessor, and before `ClearSolutions` preprocessor, so we can verify two things with this sanity check:
1. verify if the correct solution is real correct
2.  verify if the auto test cases are correctly generated

```
    preprocessors = List([
        IncludeHeaderFooter,
        InstantiateTests,
        Execute,
        LockCells,
        ClearSolutions,
        ClearOutput,
        CheckCellMetadata,
        ComputeChecksums,
        SaveCells,
        ClearHiddenTests,
        ClearMarkScheme,
        ComputeChecksums,
        CheckCellMetadata,
    ])
```

**Comment by trevorcampbell** [comment]
@wiwang looks good! I have one question: what happens if there is an error in the code? Does the Execute preprocessor just quit? Does it report an error? Basically, if there is an error, how will the instructor know what to do to fix it?

**Comment by wiwang** [comment]
@trevorcampbell  if there is a error in the code, execute preprocessor just raise a exception like below  and exit,  it don't get the running time error from kernel and print them out to give instructor which line of code introduce this error,  but I think we definitely can get this backtracking error from kernel just like jupyter notebook

`raise CellExecutionError("Receive error message from kernel")`

**Comment by trevorcampbell** [comment]
@wiwang at a minimum we need to print *both* the code that InstantiateTests created (it should just be the code in the cell that Execute sees), as well as the error that was generated by the kernel. If you can think of any other information to report that will help the instructor fix the error, add that too.

**Comment by wiwang** [comment]
@trevorcampbell  I made the code change as you describe and run some test cases to verify if this change actually work.
**test case 1: if grader make some mistake in solution cell**
the generating assignment process will print out some errors to help grader find out which code introduce this error and what kind of error it is:

```
[GenerateAssignmentApp | ERROR] Failed to run code:
    type(sum_of_squares(11))
[GenerateAssignmentApp | ERROR] Running time error is:
    name 'squares' is not defined
[GenerateAssignmentApp | ERROR] Failed to run code:
    str(sum_of_squares(11))
[GenerateAssignmentApp | ERROR] Running time error is:
    name 'squares' is not defined
```

**test case 2: if the auto generated test cases have some error:**
the `execute` preprocessor will print out similar error message as above

**Pull request merged**
